In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5,6,7,8,9])
print(a)
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)
print(type(a))

#Finding the dimensions of the array:

print(a.ndim)
print(b.ndim)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
1
2


In [3]:
# Finding bytesize of each element
print(a.itemsize)
print(b.itemsize)

#Finding the size 
print(a.size)
print(b.size)

#Finding the shape
print(a.shape)
print(b.shape)

4
4
9
9
(9,)
(3, 3)


In [4]:
c = np.array([[1,2,3,4],[5,6,7,8]])
#reshape
print(c.reshape(4,2))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [5]:
#slicing
print(a[2:-3:2])
print(a[::-1])
print(a[::2])

#slicing 2D array
print("2D array||")
print(b[1,1:2])

[3 5]
[9 8 7 6 5 4 3 2 1]
[1 3 5 7 9]
2D array||
[5]


In [6]:
#Linespacing
x = np.linspace(4,7,5)
print(x)

print(a.max())
print(a.min())
print(a.sum())

[4.   4.75 5.5  6.25 7.  ]
9
1
45


In [7]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
# Sum of whole rows amd columns
print(b.sum(axis=0)) 

[12 15 18]


In [9]:
# Finding the square root
print(np.sqrt(b))

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]


In [10]:
# standard devoation
print(np.std(b))

2.581988897471611


In [11]:
# Type Conversion

arr = np.array(['1', '2', '3'])
print(arr)
print(arr.dtype)
new_arr = arr.astype('i')
print(new_arr)
print(new_arr.dtype)

['1' '2' '3']
<U1
[1 2 3]
int32


In [12]:
# copy using NumPy

arr = np.array([1,2,3,4,5])
x = arr.copy()
print(x)

[1 2 3 4 5]


In [13]:
# view

x = arr.view()
arr[1] = 42
x[0] = 39

print(arr)
print(x)

[39 42  3  4  5]
[39 42  3  4  5]


In [15]:
# Join two array

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [18]:
# joining two 2-D array

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [21]:
# Stacking two arrays(concatenating)

a = np.array([[1,2,3],[3,4,5,]])
b = np.array([[1,2,3],[3,4,5]])

print(np.vstack((a,b)))

print(np.hstack((a,b)))

print(np.dstack((a,b)))

[[1 2 3]
 [3 4 5]
 [1 2 3]
 [3 4 5]]
[[1 2 3 1 2 3]
 [3 4 5 3 4 5]]
[[[1 1]
  [2 2]
  [3 3]]

 [[3 3]
  [4 4]
  [5 5]]]


In [25]:
# Splitting the array

arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr,3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [30]:
# Splitting 2D array

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
newarr = np.array_split(arr, 3)
print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [31]:
# Searching array

arr = np.array([1,2,3,4,5,4,4])
x = np.where(arr == 4)
print(x)

(array([3, 5, 6], dtype=int64),)


In [33]:
# Sorting array

arr = np.array([3,6,5,1,6,9,33])
print(np.sort(arr))

[ 1  3  5  6  6  9 33]


### Random Numbers in Numpy

In [34]:
from numpy import random
x = random.randint(100)
print(x)

86


In [36]:
x = random.rand()
print(x) # 0 to 1

0.8006621964200333


In [38]:
# generating random array

x = random.randint(100,size=(5,3))
print(x)

[[73 63 98]
 [80 39 59]
 [85 28 61]
 [94 40  4]
 [38 95 88]]


In [39]:
# with choice

x = random.choice([3,4,5,1])
print(x)

5


In [41]:
# Generating Normal Distribution

# loc - (Mean) where the peak of the bell exists
# scale - (Standard Deviation) how flat the graph distribution should be
# size - The shape of the returned array


x = random.normal(size=(2,3))
print(x)

[[ 2.0976164   0.55265242 -0.88187404]
 [-0.38388912  1.03775113 -0.32428242]]


In [42]:
# normal distribution with mean at 1 and standard deviation of 2

x = random.normal(loc=1,scale=2,size=(2,3))
print(x)

[[ 2.75503079 -0.03682081  0.22349219]
 [ 1.07812426  0.52822197  1.39631599]]


In [ ]:
# visualising Normal Distribution using matplotlib and seaborn

import matplotlib.pyplot as plt
import seaborn as sns

sns.distplot(random.normal(size=1000),hist=False)
plt.show