In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
from sklearn.linear_model import LinearRegression

In [2]:
data = pd.read_csv('real_estate_price_size.csv')
data.head()

price     size
0  234314.144   643.09
1  228581.528   656.22
2  281626.336   487.29
3  401255.608  1504.75
4  458674.256  1275.46

In [3]:
x = data['size']
y = data['price']

In [4]:
x.shape

(100,)

In [5]:
y.shape

(100,)

In [8]:
x_matrix = x.values.reshape(-1,1)
x_matrix

array([[ 643.09],
       [ 656.22],
       [ 487.29],
       [1504.75],
       [1275.46],
       [ 575.19],
       [ 570.89],
       [ 620.82],
       [ 682.26],
       [ 694.52],
       [1060.36],
       [1842.51],
       [ 694.52],
       [1009.25],
       [1300.96],
       [1379.72],
       [ 690.54],
       [ 623.94],
       [ 681.07],
       [1027.76],
       [ 620.71],
       [ 549.69],
       [1207.45],
       [ 518.38],
       [ 525.81],
       [1103.3 ],
       [ 570.89],
       [1334.1 ],
       [ 681.07],
       [1496.36],
       [1010.33],
       [ 681.07],
       [ 597.9 ],
       [ 525.81],
       [ 857.54],
       [ 622.97],
       [ 823.21],
       [ 570.25],
       [ 685.48],
       [ 698.29],
       [1021.95],
       [ 682.26],
       [ 823.21],
       [1334.1 ],
       [1060.36],
       [ 698.29],
       [ 633.19],
       [ 698.29],
       [ 633.19],
       [ 617.05],
       [ 647.5 ],
       [1021.95],
       [1021.95],
       [ 727.88],
       [ 647.5 ],
       [15

In [20]:
reg = LinearRegression()

In [21]:
reg.fit(x_matrix,y)

LinearRegression()

In [22]:
reg.score(x_matrix,y)

0.7447391865847587

In [23]:
reg.coef_

array([223.17874259])

In [24]:
reg.intercept_

101912.60180122912

In [28]:
x_temp = np.array([1000.00,750.0])
x_temp = x_temp.reshape(2,-1)
reg.predict(x_temp)


array([325091.34439584, 269296.65874718])